# Generated by Django 5.1.1 on 2024-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
