# Generated by Django 5.1.1 on 2024-10-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_ip_address_post_user_agent_post_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
